[*] Running ...
[*] Dataset loaded: C:\Development\cs5491-artificial-intelligence/problems/tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "C:\Development\cs5491-artificial-intelligence/problems/tsp_constructive/eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\cs5491-artificial-intelligence/problems/tsp_constructive/eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
                ^^^^^^^^^^^^^^^^^
  File "C:\Development\cs5491-artificial-intelligence\problems\tsp_constructive\gpt.py", line 17, in select_next_node_v2
    next_std_dev_distance_to_unvisited = np.std(next_distances)
           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'next_node' where it is not associated with a value
