[*] Running ...
[*] Dataset loaded: C:\Development\cs5491-artificial-intelligence/problems/tsp_constructive\dataset\train50_dataset.npy with 64 instances.
C:\Users\sunscreenDuckDuck\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\sunscreenDuckDuck\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
C:\Users\sunscreenDuckDuck\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\sunscreenDuckDuck\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
C:\Users\sunscreenDuckDuck\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
[*] Instance 0: 6.328058240996392
[*] Instance 1: 8.021375366315466
[*] Instance 2: 9.251018407838881
[*] Instance 3: 8.306424161584145
[*] Instance 4: 8.167438817106484
[*] Instance 5: 8.719218931854881
[*] Instance 6: 9.71882825280313
[*] Instance 7: 8.49365965786146
[*] Instance 8: 7.801103295753772
[*] Instance 9: 9.454010383964146
[*] Instance 10: 8.392632150080278
[*] Instance 11: 8.13734525877742
[*] Instance 12: 7.421120475088488
[*] Instance 13: 8.122453162412693
[*] Instance 14: 8.989759421361741
[*] Instance 15: 7.503523752423795
[*] Instance 16: 8.745107149962921
[*] Instance 17: 6.41017364685742
[*] Instance 18: 9.825024577529016
[*] Instance 19: 7.009871776364225
